### PR TITLE
Add Message CID to SendFilResponse

### PR DESCRIPTION
**Pull request by hoffmabc**
This would allow clients to retrieve the message CID for sending FIL.

### CODE REVIEW

**Comment by asutula** [comment]
Great @hoffmabc, I've been wanting to make this addition as well. Just just last week started using the `develop` branch for all new features... Can you rebase your branch against `develop` and change the target branch for this PR then we can move forward? Thanks!

**Comment by hoffmabc** [comment]
Alright @asutula I rebased and put it against /develop.

**Comment by asutula** [comment]
Looking great! Only think missing I noticed is update the cli `send` commands in the user and admin parts of the cli `pow` subcommands. Those commands currently don't print any output... would be useful to print the cid, right?

**Comment by hoffmabc** [comment]
Good suggestion. I'll add it.

**Comment by asutula** [comment]
Quickest way is just to print out the json representation of the client response. You could steal that code from any number of other commands that do that.

**Review by asutula — APPROVED** [review]
Looks great. Thanks @hoffmabc!

**Pull request merged**
